import {StyleSheet} from 'react-native';
import R from 'resources/R';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    flexDirection: 'column',
    backgroundColor: '#17253d',
  },
  topBar: {borderWidth: 2, flex: 0.5},
  mapContainer: {
    flex: 5,
    justifyContent: 'center',
  },
  text: {
    textAlign: 'center',
  },
  mapStyle: {
    flex: 1,
  },
  backBtn: {
    position: 'absolute',
    zIndex: 999,
    padding: 10,
    borderRadius: 15,
    top: 20,
    left: 10,
    // borderWidth: 1,
    // borderColor: 'white',
  },
  drawerArea: {
    position: 'absolute',
    zIndex: 999,
    paddingVertical: 10,
    paddingHorizontal: 20,
  },
  drawerButton: {height: 50, width: 50, borderRadius: 50},
  modalHeaderText: {
    color: R.colors.PRIMARI_DARK,
    textAlign: 'center',
    fontFamily: R.fonts.Regular,
    fontSize: R.fontSize.S,
    paddingVertical: 10,
    marginBottom: 10,
  },
  backgroundColor: {
    paddingVertical: 5,
  },
  modalContainer: {
    justifyContent: 'flex-end',
    margin: 20,
    borderRadius: 20,
    overflow: 'hidden',
  },
  // modalInnerContainer: {
  //   backgroundColor: 'white',
  //   maxHeight: 150,
  //   borderRadius: 20,
  //   justifyContent: 'space-between',
  //   padding: 10,
  // },
  modalFooterText: {
    flexDirection: 'row',
    marginHorizontal: 30,
  },
  bottomArea: {
    position: 'absolute',
    paddingHorizontal: 20,
    paddingVertical: 30,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    borderRadius: 10,
    width: '100%',
    height: 170,
    bottom: 0,
    backgroundColor: 'white',
  },
  titleArea: {
    alignItems: 'center',
    marginBottom: 20,
  },
  titleText: {
    fontFamily: R.fonts.Bold,
    fontSize: R.fontSize.M,
    color: R.colors.PRIMARI_DARK,
  },
  buttonArea: {},
  input: {
    // flex: 1,
    height: '90%',
    borderRadius: 10,
    borderWidth: 1,
    marginHorizontal: 40,
    marginVertical: 20,
    borderColor: 'grey',
    textAlignVertical: 'top',
    color: R.colors.PRIMARI_DARK,
    fontSize: 16,
    padding: 10,
  },
  feedback: {
    height: '50%',
  },
  // modalContainer: {
  //   justifyContent: 'flex-end',
  //   margin: 0,
  //   borderRadius: 20,
  //   overflow: 'hidden',
  // },
  modalInnerContainer: {
    backgroundColor: 'white',
    maxHeight: '30%',
    justifyContent: 'space-around',
    padding: 10,
    flexDirection: 'column',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
  },
  innerContainer: {
    // flexDirection: 'row',
    marginRight: 10,
    flex: 1,
    justifyContent: 'space-around',
  },
  profileContainer: {
    flexDirection: 'column',
  },
  name: {
    fontSize: R.fontSize.XL,
    textAlign: 'center',
    fontFamily: R.fonts.Bold,
    color: R.colors.PRIMARI_DARK,
  },
  starContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
  },
  innerStarContainer: {
    flexDirection: 'row',
  },
  rating: {
    color: R.colors.PRIMARI_DARK,
  },
  reviewCount: {
    color: R.colors.LIGHTBLUE,
    marginLeft: 10,
  },
  imgContainer: {
    flexDirection: 'row',
  },
  image: {
    height: 100,
    width: 80,
    borderRadius: 200,
    // borderWidth: 1,
  },
  icon: {
    alignSelf: 'center',
    marginLeft: 30,
  },
  buttonContainer: {
    flexDirection: 'row',
    marginTop: 20,
    marginBottom: 20,
  },
  buttonInner: {
    flex: 1,
    width: '100%',
    marginHorizontal: 10,
  },
  viewJob: {
    alignSelf: 'center',
    position: 'absolute',
    zIndex: 999,
    // padding: 10,
    borderRadius: 15,
    bottom: 20,
  },
  heading: {
    color: R.colors.PRIMARI_DARK,
    fontFamily: R.fonts.Bold,
    fontSize: R.fontSize.XL,
    textAlign: 'center',
    marginTop: 10,
  },
  buttonsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginTop: 30,
    marginBottom: 20,
  },
  // innerContainer: {flex: 1, marginRight: 5},
  candidateContainer: {flex: 1, marginRight: 5},
  candidateContainerSecond: {flex: 1, marginRight: 5},
  circle: {
    height: 15,
    width: 15,
    alignSelf: 'flex-end',
    borderRadius: 20,
    backgroundColor: R.colors.RED,
    top: -15,
    position: 'absolute',
    zIndex: 999,
  },
  jobAcceptedContainer: {
    backgroundColor: 'white',
    height: '25%',
    borderTopRightRadius: 20,
    borderTopLeftRadius: 20,
    justifyContent: 'space-around',
    padding: 10,
    flexDirection: 'column',
  },
  providerContainer: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    width: '40%',
    alignSelf: 'center',
  },
  kindaView: {flexDirection: 'column', justifyContent: 'center'},
  kindajobsTitle: {
    fontFamily: R.fonts.Bold,
    fontSize: R.fontSize.L,
    alignItems: 'center',
    color: R.colors.PRIMARI_DARK,
    flexDirection: 'row',
    justifyContent: 'center',
  },
});

export default styles;
